# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm install --force
      
      - name: Test
        continue-on-error: true
        run: |
          export NODE_OPTIONS="--max_old_space_size=4096"
          npm test

      - name: Build and Pack
        continue-on-error: true
        run: |
          export NODE_OPTIONS="--max_old_space_size=4096"
          npm run build
          npm run pack
